version: 2
jobs:
  build:
    working_directory: ~/angular-projects
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-projects-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: angular-projects-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # Just test the library project for now.
      - run: npm run test -- library --no-watch --no-progress --browsers=ChromeHeadlessCI
      #- run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
